### ISSUE TITLE
May I ask what font you are using in your screenshot?

### ISSUE THREAD

**Issue by whxcode** [olimorris/dotfiles#10]
<img width="1036" alt="image" src="https://github.com/olimorris/dotfiles/assets/44012914/139d5942-d7e5-4dff-9ba2-0e105064fd74">

**Comment by olimorris** [comment]
I'm using the epic [Operator Mono](https://www.typography.com/blog/introducing-operator). The italics can't be beaten imo:

![2024-05-06 09_53_05 - WezTerm@2x](https://github.com/olimorris/dotfiles/assets/9512444/d2ea66fe-c75c-4252-af97-a8e35f2d39ab)

**Comment by whxcode** [comment]
> I'm using the epic [Operator Mono](https://www.typography.com/blog/introducing-operator). The italics can't be beaten imo:

Could you please share the Operator Mono font you're using? I really like the font style in your screenshot and I'd like to try it out. Thank you!

**Comment by olimorris** [comment]
It's a paid for font unfortunately. I think I paid $200 back in the day.

**Comment by whxcode** [comment]
> It's a paid for font unfortunately. I think I paid $200 back in the day.
> 
> Check out my Wezterm config the styles of the font I'm using.

Anyway, thank you
