### ISSUE TITLE
Floating tmux status bar

### ISSUE THREAD

**Issue by neohunter** [olimorris/dotfiles#8]
Hey, I noticed that in your pomodoro tmux plugin you have some kind of floating tmux status bar, how you achieve that?

**Comment by olimorris** [comment]
I don't think I'm doing anything out of the ordinary. It might just be the padding I have in my kitty config.

My exact tmux status bar can be found [here](https://github.com/olimorris/dotfiles/tree/main/.config/tmux):

<img width="1510" alt="Screen Shot 2023-04-07 at 21 38 11@2x" src="https://user-images.githubusercontent.com/9512444/230675784-ee565f0b-1ac3-4d31-99ec-174e3ae5e70d.png">

Depending on how you work, you might like my `tmux-sessionizer` file, [here](https://github.com/olimorris/dotfiles/blob/main/bin/tmux-sessionizer).
