### ISSUE TITLE
[Question] Why are you setting up stylua in efm when you have lua_ls installed, I think lua_ls also had formatting function...

### ISSUE THREAD

**Issue by 1m-N00b** [olimorris/dotfiles#9]

**Comment by olimorris** [comment]
Yes it does. I only know stylua so just stuck with that

**Comment by 1m-N00b** [comment]
Is this format of lua_ls not good enough?
https://github.com/LuaLS/lua-language-server/wiki/Formatter#lua

**Comment by olimorris** [comment]
No idea. As long as it works and formats your code, you're good 😄
